#!/bin/bash

TESTS="${TESTS} full"
TESTS="${TESTS} auto"
TESTS="${TESTS} minimal"
TESTS="${TESTS} master-full"
TESTS="${TESTS} no-nls"
TESTS="${TESTS} no-edit"
TESTS="${TESTS} vfstest.no-vfs"
TESTS="${TESTS} vfstest.only-fish"
TESTS="${TESTS} vfstest.only-sfs"
TESTS="${TESTS} vfstest.only-cpio"
TESTS="${TESTS} vfstest.only-ftp"
TESTS="${TESTS} vfstest.only-extfs"
TESTS="${TESTS} vfstest.only-tar"
TESTS="${TESTS} vfstest.only-undelfs"
TESTS="${TESTS} vfstest.only-mcfs"
TESTS="${TESTS} vfstest.only-smbfs"
TESTS="${TESTS} vfstest.only-mcserver"
TESTS="${TESTS} vfstest.only-mvfs-9p"
TESTS="${TESTS} 1775_mvfs_9P.minimal"
TESTS="${TESTS} 1775_mvfs_9P.full"

BRANCH="mco/1818_refactoring_no_vfs_METUX"
ID="1818_refactoring_no_vfs_METUX"

. _run_test.sh
