#!/bin/bash

TESTS="${TESTS} full"
TESTS="${TESTS} auto"
TESTS="${TESTS} minimal"
TESTS="${TESTS} master-full"
TESTS="${TESTS} no-nls"
TESTS="${TESTS} no-edit"
TESTS="${TESTS} vfstest.no-vfs"
TESTS="${TESTS} vfstest.only-fish"
TESTS="${TESTS} vfstest.only-sfs"
TESTS="${TESTS} vfstest.only-cpio"
TESTS="${TESTS} vfstest.only-ftp"
TESTS="${TESTS} vfstest.only-extfs"
TESTS="${TESTS} vfstest.only-tar"
TESTS="${TESTS} vfstest.only-undelfs"
TESTS="${TESTS} vfstest.only-mcfs"
TESTS="${TESTS} vfstest.only-smbfs"
TESTS="${TESTS} vfstest.only-mcserver"
TESTS="${TESTS} vfstest.only-mvfs-9p"

BRANCH="mco/1925_mcserver_conditional"
ID="1925_mcserver_conditional"

TESTFARM_CFLAGS="-O -Wwrite-strings"

. _run_test.sh
